### ISSUE TITLE
BAR chart Rotate

### ISSUE THREAD

**Issue by tamilanmanikandan** [Zomato/DR-charts#11]
![screen shot 2016-11-11 at 12 33 47 pm](https://cloud.githubusercontent.com/assets/7071499/20207526/d7312886-a80d-11e6-85af-72633847de8c.png)->
![screen shot 2016-11-11 at 12 40 19 pm](https://cloud.githubusercontent.com/assets/7071499/20207534/e5f962ac-a80d-11e6-8d6f-dc3240e864ec.png)

i just wanna rotate bar view form x axis to y axis..
how to solve this

**Comment by dhirenthirani** [comment]
Hiiiiii,
No, We can't do this till now
I am working on it 
Will let you know wen its completed.

Thanks for interest

**Comment by tamilanmanikandan** [comment]
any other chart library do you know to do this?...
kindly suggest me...
