### ISSUE TITLE
Curved in line chart

### ISSUE THREAD

**Issue by anismansuri** [Zomato/DR-charts#14]
In line chart i want to make it curved as per requirement.
Is there any properties for it?

**Comment by mrimadali** [comment]
+1

**Comment by mrimadali** [comment]
+1

**Comment by dhirenthirani** [comment]
I ll see for that property if its not there ll add one.
Thanks for ur interest in Dr-Charts

**Comment by mrugeshtank** [comment]
How can I use line chart with curved, now?
