### ISSUE TITLE
Reset graph

### ISSUE THREAD

**Issue by Elvereth** [Zomato/DR-charts#18]
Hello!

It might be a silly question, but is there a way to reset/clear the graph previosly drawn?
I'm working on the same view and drawing different graphs when a button get clicked.

That's how it looks after I try to redraw it:
![fullsizerender](https://cloud.githubusercontent.com/assets/16473783/23453323/3d10b670-fe68-11e6-8d7d-839515fb705a.jpg)
I tried to reset the view in some ways, but without any luck.

If there isn't the possibility to reset the chart I suggest to insert it, cause it might be useful.

Thanks

**Comment by dhirenthirani** [comment]
Hey,
Ya we can do this by just calling a method which is there in the class.
i.e. "reloadGraph"

Thanks for your interest in Dr-Charts.

**Comment by Elvereth** [comment]
Hi,
sorry, for some reason I totally didn't see it. I knew it had to be there somewhere.
Thanks for the quick reply!

**Comment by dhirenthirani** [comment]
Hey,
Not an issue.
Thanks for interest in Dr-Charts.
