### ISSUE TITLE
issue report

### ISSUE THREAD

**Issue by iceman201** [Zomato/DR-charts#4]
```
Analyzing dependencies
Pre-downloading: `drCharts` from `https://github.com/Zomato/DR-charts.git`
[!] The `drCharts` pod failed to validate due to 1 error:
    - WARN  | github_sources: Github repositories should end in `.git`.
    - ERROR | description: The description is empty.
```

**Comment by dhirenthirani** [comment]
Hey, 
Sorry for late reply.
I am also using the pod to install the charts. I did not face this problem.
Can you please elaborate on this. So that i can understand the exact issue.
Thanks for your interest in Dr-Charts.

**Comment by iceman201** [comment]
i was used the same code as you post on description into my podfile, and run `pod install`

> pod 'drCharts', :git => 'https://github.com/Zomato/DR-charts.git'

after the terminal give me the error message as display on the top.

**Comment by dhirenthirani** [comment]
Hey, 
You can check it now, I think it should work.
I tested it on my side.
If you find any problems, i am always there to help.
Thanks for your interest in Dr-Charts.

**Comment by vijayhfs** [comment]
How to manage long text labels on x-axis? in my case those get cut down.
