### ISSUE TITLE
[question] Is it possible to make a logarithmic axis

### ISSUE THREAD

**Issue by dodikk** [Zomato/DR-charts#5]
Dear author, thanks for a great work.
I need to implement the [following chart](https://gist.github.com/dodikk/dbad6675a7ead2d322ced451495cac09) and I wonder if it's feasible with your library.

I have not found any examples or discussions of **logarithmic axis** while searching with google and StackOverflow, so I'm asking here.

Thanks in advance.

**Comment by dhirenthirani** [comment]
hey,
Sorry for late reply.
Yes you can create the logarithmic axis using the Multiline graph, you can create the line with the same but if you are asking it for 3D then that feature is still not there. You can hope for this coming soon.
But I am not clear with your requirement till now.

Thanks for your intrest in Dr-Chart.
